<?php
$themeSettingConfig = $this->helper('MGS\ThemeSettings\Helper\Config');
$_headerAbsolute = $themeSettingConfig->getStoreConfig('themesettings/header/header_absolute');
$stickyMenu = $themeSettingConfig->getStoreConfig('themesettings/header/sticky_menu');
?>
<?php if ($_headerAbsolute): ?>
    <div id="placeholder-header"></div>
<?php else: ?>
    <div id="placeholder-header" class="absolute-header"></div>
<?php endif; ?>

<?php if ($_headerAbsolute): ?>
<script>
    function arrowGetHeaderHeight() {
        var pageHeader = document.querySelector('.page-header');
        if (pageHeader) {
            var height_header = pageHeader.offsetHeight;
            document.querySelector('#placeholder-header').style.height = height_header + 'px';
        } else {
            console.error("Элемент .page-header не найден на странице.");
        }
    }

    document.addEventListener('DOMContentLoaded', function() {
        arrowGetHeaderHeight();
        window.addEventListener('resize', arrowGetHeaderHeight);
        window.addEventListener('load', arrowGetHeaderHeight);
    });
</script>

<?php endif; ?>
