<?php

use Arpo\MigrationCustomer\Block\TotalWeightBlock;

/** @var TotalWeightBlock $block */
?>

<div class="custom-weight">
<!--    <h3>вес:</h3> <h3 class="weight-items">--><?php //echo round($weight, 0). 'гр'?><!--</h3>-->
<!--    <h3>вес:</h3> <h3 class="weight-items">--><?php //echo round($weight, 0).'<span class="AdditionalWeight"></span> гр'?><!--</h3>-->
<!--    <h3>вес:</h3>-->
<!--    <h3>--><?php //echo $desc?><!--</h3>-->
</div>
